<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\sample-data\**" />
    <Content Remove="wwwroot\sample-data\**" />
    <EmbeddedResource Remove="wwwroot\sample-data\**" />
    <None Remove="wwwroot\sample-data\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlazorSortable" Version="8.1.0" />
    <PackageReference Include="Cropper.Blazor" Version="1.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.7" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="10.0.8" />
    <PackageReference Include="MudBlazor" Version="9.5.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JustTaskTracker.WebUI.Domain\JustTaskTracker.WebUI.Domain.csproj" />
    <ProjectReference Include="..\JustTaskTracker.WebUI.Services.Abstractions\JustTaskTracker.WebUI.Services.Abstractions.csproj" />
    <ProjectReference Include="..\JustTaskTracker.WebUI.Services\JustTaskTracker.WebUI.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
    <TrimmerRootAssembly Include="Microsoft.Authentication.WebAssembly.Msal" />
    <TrimmerRootDescriptor Include="Trimmer.xml" />
  </ItemGroup>

</Project>
